# Generated by Django 5.0.1 on 2025-11-27 18:04

import django.db.models.deletion
import django.utils.timezone
import recordings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoughRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anonymous_name', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_file', models.FileField(upload_to=recordings.models.upload_to)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_format', models.CharField(max_length=10)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('recording_method', models.CharField(choices=[('browser', 'Browser Recording'), ('upload', 'File Upload')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('bit_rate', models.IntegerField(blank=True, null=True)),
                ('channels', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cough Recording',
                'verbose_name_plural': 'Cough Recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
